CREATE TABLE users (
    id INT PRIMARY KEY IDENTITY(1,1),
    name NVARCHAR(100) NOT NULL,
    username NVARCHAR(100) NOT NULL UNIQUE,
    password NVARCHAR(100) NOT NULL,
    created_at DATETIME2 DEFAULT SYSDATETIME(),
    updated_at DATETIME2 DEFAULT SYSDATETIME()
);

CREATE TABLE blogs (
    id INT PRIMARY KEY IDENTITY(1,1),
    author NVARCHAR(255),
    url NVARCHAR(255) NOT NULL,
    title NVARCHAR(255) NOT NULL,
    likes INT DEFAULT 0,
    userid INT,
    FOREIGN KEY (userid) REFERENCES users(id)
);

CREATE TABLE reading_list (
  id INT IDENTITY(1,1) PRIMARY KEY,
  user_id INT FOREIGN KEY REFERENCES users(id),
  blog_id INT FOREIGN KEY REFERENCES blogs(id),
  is_read BIT DEFAULT 0
);

-- Add columns to existing blogs table
ALTER TABLE blogs ADD description NVARCHAR(500);
ALTER TABLE blogs ADD content NVARCHAR(MAX);
ALTER TABLE blogs ADD image_url NVARCHAR(500);
ALTER TABLE blogs ADD category NVARCHAR(100);
ALTER TABLE blogs ADD views INT DEFAULT 0;
ALTER TABLE blogs ADD is_published BIT DEFAULT 1;
ALTER TABLE blogs ADD created_at DATETIME2 DEFAULT SYSDATETIME();
ALTER TABLE blogs ADD updated_at DATETIME2 DEFAULT SYSDATETIME();

